name: KN-rates
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - appdirs 
  - blas  
  - bottleneck 
  - brotli 
  - brotli-bin 
  - brotlipy 
  - bzip2 
  - ca-certificates 
  - certifi 
  - cffi 
  - charset-normalizer 
  - contourpy 
  - cryptography 
  - cycler 
  - extinction 
  - fonttools 
  - freetype 
  - giflib 
  - idna 
  - joblib 
  - jpeg
  - kiwisolver 
  - lcms2 
  - lerc 
  - libbrotlicommon 
  - libbrotlidec 
  - libbrotlienc 
  - libcxx
  - libdeflate 
  - libexpat 
  - libffi 
  - libgfortran 
  - libgfortran5 
  - libopenblas 
  - libpng 
  - libsqlite 
  - libtiff 
  - libwebp 
  - libwebp-base 
  - libzlib 
  - llvm-openmp 
  - lz4-c
  - matplotlib
  - matplotlib-base
  - mpi
  - mpi4py
  - munkres
  - ncurses
  - numexpr
  - openmpi
  - openssl
  - packaging
  - pandas
  - pillow
  - pip
  - pooch
  - pycparser
  - pyerfa
  - pyopenssl
  - pyparsing
  - pysocks
  - python=3.11.4
  - python-dateutil
  - python_abi
  - pytz
  - pyyaml
  - readline
  - requests
  - schwimmbad
  - scipy
  - seaborn
  - setuptools
  - six
  - sncosmo
  - sqlite
  - threadpoolctl
  - tk
  - tornado
  - tqdm
  - tzdata
  - urllib3
  - wheel
  - xz
  - yaml
  - zlib
  - zstd
  - pip:
      - afterglowpy
      - astropy
      - cython
      - dnspython
      - george
      - gpstime
      - gwemlightcurves
      - h5py
      - iniconfig
      - inspiral-range
      - kilopop
      - lalsuite
      - ligo-em-bright
      - ligo-segments
      - lscsoft-glue
      - numpy
      - penquins
      - pluggy
      - pymongo
      - pymultinest
      - pyrxp
      - pytest
      - scikit-learn
      - sfdmap

